"""create Cupcakes table

Revision ID: d92d7994d7f8
Revises: 
Create Date: 2016-08-17 12:14:43.538284

"""

# revision identifiers, used by Alembic.
revision = 'd92d7994d7f8'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupcakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delicious', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupcakes')
    ### end Alembic commands ###


